"""manual profile overrides

Revision ID: 2f895c75588d
Revises: e98e8ac7efec
Create Date: 2026-08-05 04:16:16.807029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f895c75588d'
down_revision: Union[str, Sequence[str], None] = '6e3b6d6f5875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('manual_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'manual_overrides')
    # ### end Alembic commands ###
