"""community reported outcome evidence tier

Revision ID: 49e99f2f0ad1
Revises: 4e4dc6b13b10
Create Date: 2026-08-06 02:35:12.302414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e99f2f0ad1'
down_revision: Union[str, Sequence[str], None] = '4e4dc6b13b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('community_outcome_evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'community_outcome_evidence')
    # ### end Alembic commands ###
