"""canonical program resolution and structured requirements

Revision ID: 4e4dc6b13b10
Revises: 2f895c75588d
Create Date: 2026-08-05 20:30:34.421367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4dc6b13b10'
down_revision: Union[str, Sequence[str], None] = '2f895c75588d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('canonical_university', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('canonical_program', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('program_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'program_url')
    op.drop_column('programs', 'canonical_program')
    op.drop_column('programs', 'canonical_university')
    # ### end Alembic commands ###
