"""historical applications

Revision ID: 6e3b6d6f5875
Revises: c31a7e42f9b1
Create Date: 2026-08-06 02:41:11.461905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3b6d6f5875'
down_revision: Union[str, Sequence[str], None] = 'c31a7e42f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_university', sa.String(), nullable=False),
    sa.Column('canonical_program', sa.String(), nullable=False),
    sa.Column('application_year', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('gpa_value', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('gpa_normalized', sa.Float(), nullable=True),
    sa.Column('gre_total', sa.Integer(), nullable=True),
    sa.Column('gre_quant', sa.Integer(), nullable=True),
    sa.Column('gre_verbal', sa.Integer(), nullable=True),
    sa.Column('toefl', sa.Integer(), nullable=True),
    sa.Column('ielts', sa.Float(), nullable=True),
    sa.Column('undergraduate_major', sa.String(), nullable=True),
    sa.Column('undergraduate_country', sa.String(), nullable=True),
    sa.Column('research_experience', sa.Boolean(), nullable=True),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('work_experience_months', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_applications_canonical_program'), 'historical_applications', ['canonical_program'], unique=False)
    op.create_index(op.f('ix_historical_applications_canonical_university'), 'historical_applications', ['canonical_university'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_applications_canonical_university'), table_name='historical_applications')
    op.drop_index(op.f('ix_historical_applications_canonical_program'), table_name='historical_applications')
    op.drop_table('historical_applications')
    # ### end Alembic commands ###
