"""isolate user-provided program data from shared cache

Revision ID: a695242f983c
Revises: 49e99f2f0ad1
Create Date: 2026-08-06 07:03:21.396892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a695242f983c'
down_revision: Union[str, Sequence[str], None] = '49e99f2f0ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'programs',
        sa.Column('user_provided_only', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('programs', 'user_provided_only', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'user_provided_only')
    # ### end Alembic commands ###
