"""multi-document profiles

Revision ID: e98e8ac7efec
Revises: bd6f55d8bc74
Create Date: 2026-08-05 03:31:45.180134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98e8ac7efec'
down_revision: Union[str, Sequence[str], None] = 'bd6f55d8bc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('student_profiles', 'raw_text')
    op.drop_column('student_profiles', 'source_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('source_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('student_profiles', 'updated_at')
    op.drop_table('documents')
    # ### end Alembic commands ###
